### ISSUE TITLE
Error when using it

### ISSUE THREAD

**Issue by zSynctic** [Akascape/CTkToolTip#13]
I already used the ctktooltip before but now when I'm using it I'm getting an error even though I did the same thing but its working in a different project of mine.

I get this error: Exception has occurred: TypeError
'CTkLabel' object is not callable

thanks
![image](https://github.com/Akascape/CTkToolTip/assets/71632495/e4a0ec8a-b637-4ecf-a2ee-176d7ac9206b)

**Comment by Akascape** [comment]
@zSynctic Not a ctktooltip issue ig. Please provide the full error in line/file.

**Comment by idiotcommerce** [comment]
this code is working fine. you provide above code is not in you library. and which file gettign error. how anyone know.
invalid

**Comment by zSynctic** [comment]
> @zSynctic Not a ctktooltip issue ig. Please provide the full error of line/file. And also update to latest version.

Exception has occurred: TypeError
'CTkLabel' object is not callable
  File "D:\Python Programming\Projects\**\*.py", line 88, in __init__
    self.tooltipsettings = CTkToolTip(self.settingsbtn, message="Settings", delay=0)
  File "D:\Python Programming\Projects\**\*.py", line 500, in <module>
    app = App()
TypeError: 'CTkLabel' object is not callable

**Comment by zSynctic** [comment]
> this code is working fine. you provide above code is not in you library. and which file getting error. how anyone know. invalid

Sorry I don't understand what you meant, the libraries importing are just fine and this project was always working only when I add the tooltip it doesn't work somehow

**Comment by Akascape** [comment]
@zSynctic I guess you have a label named as CTkToolTip in your project. That is why you are getting this type error. Find it and change the name of that label.

**Comment by idiotcommerce** [comment]
![image](https://github.com/Akascape/CTkToolTip/assets/121589808/d7fb6aed-ddce-4b78-9c13-c3aa7a7217ff)

this is your file structed in github. mabe some name type error. please check it

**Comment by zSynctic** [comment]
> @zSynctic I guess you have a label named as CTkToolTip in your project. That is why you are getting this type error, as it is assuming the ctktooltip as a ctklabel. Find it and change the name of that label.

Just checked that the only things named ctktooltip in my project are the importing of the library and this one

**Comment by Akascape** [comment]
@zSynctic, is the basic example also showing this error in your machine? If not, then the problem is somewhere in your code.

**Comment by zSynctic** [comment]
no app is not a ctklabel also the ctktooltip worked fine in my other project so I don't know what is the issue, I removed the ctktooltip and it seems even ctktoplevel has a problem even though it works it shows some issues tried fixing it or searching for any problem in the code can't find anything might try uninstalling both ctktooltip and customtkinter and downloading them both again

**Comment by Akascape** [comment]
@zSynctic Try updating the ctktooltip package.

**Comment by zSynctic** [comment]
Sadly I'm still getting the same issue. also here is my error for ctktoplevel:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\**\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\**\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", 
line 554, in _clicked
    self._command()
  File "D:\Python Programming\Projects\*\**.py", line 244, in showSett
    self.settingsview = customtkinter.CTkToplevel(self, fg_color="dark_color")
  File "C:\Users\**\AppData\Local\Programs\Python\Python310\lib\site-packages\customtkinter\windows\ctk_toplevel.py", line 36, in __init__
    super().__init__(*args, **pop_from_dict_by_set(kwargs, self._valid_tk_toplevel_arguments))
  File "C:\Users\**\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 2653, in __init__
    self.title(root.title())
TypeError: 'CTkLabel' object is not callable

**Comment by Akascape** [comment]
@zSynctic
I can't do anything with this issue. You have to give a minimal example which causes this problem. Otherwise there is fault in your code only. The error logs are also not sufficient to figure out the bug. This type error generally occurs when you try to call a CTkLabel class variable. Thoroughly check the `showSett` function/class of your project.

**Comment by Akascape** [comment]
@zSynctic
I can't do anything with this issue. You have to give a minimal example which causes this problem. Otherwise there is fault in your code only as I am unable to produce this error. The error logs are also not sufficient to figure out the bug. This type error generally occurs when you try to call a CTkLabel object. Thoroughly check the `showSett` function/class of your project.

**Comment by idiotcommerce** [comment]
i think there may be problem please check it. 

![image](https://github.com/Akascape/CTkToolTip/assets/121589808/f67a642e-500a-45e2-a74a-437c57063ee8)

**Comment by zSynctic** [comment]
thanks

**Comment by idiotcommerce** [comment]
Have a great day.
