### ISSUE TITLE
tooltip showing up under frame

### ISSUE THREAD

**Issue by kosh66** [Akascape/CTkToolTip#14]
Hi, I have a set of buttons on a subframe of a main frame. The tooltip for the associated buttons is showing up under the button, as it its stuck on the  main frame.

**Comment by Akascape** [comment]
@kosh66 can you give me minimal example?

**Comment by kosh66** [comment]
Apologies for late reply.  That would be difficult to do a minimal example at this time. . I have now noticed it also occurs with the basic tkinter tootips widget as well. I think the issue is that I have a main window then I open a MDI window sitting on top which cannot be minimised etc.  I feel that the tooltip is appearing on the main window, not the sub window and hence it seems to get covered.
