### ISSUE TITLE
does not work with treeview

### ISSUE THREAD

**Issue by DanielVieira326** [Akascape/CTkToolTip#15]
Code:

self.tree.bind("<Motion>", self.Show_desc)

def Show_desc(self,event):#tree.bind("<Motion>", Show_desc) 
        self.y = self.tree.identify_row(event.y)
        self.x = self.tree.identify_column(event.x)
        self.prevalues=self.tree.item(self.y)
        self.values=self.prevalues['values']
        if self.x =="#2":
            self.tip_row=CTkToolTip(self.tree.identify_row(event.y), message=f"{self.values[1]}")
        if self.x =="#4":
            self.tip_row=CTkToolTip(self.tree.identify_row(event.y), message=f"{self.values[3]}")

Error:

File "c:\Users\daniel.vieira\Desktop\AiUni\App\app\Faturamento\Fat_import.py", line 665, in Show_desc
    self.tip_row=CTkToolTip(self.tree.identify_row(event.y), message=f"{self.values[3]}")
  File "C:\Users\daniel.vieira\Anaconda3\lib\site-packages\CTkToolTip\ctk_tooltip.py", line 42, in __init__
    self.transparent_color = self.widget._apply_appearance_mode(
AttributeError: 'str' object has no attribute '_apply_appearance_mode'

**Comment by Akascape** [comment]
@DanielVieira326 This widget is only for ctk widgets and not for tkinter ones.
