### ISSUE TITLE
CtkTooltip on CTkSegmentedButton

### ISSUE THREAD

**Issue by jipen** [Akascape/CTkToolTip#25]
...Doesn't work.

As on [ctk_tooltip.py](https://github.com/Akascape/CTkToolTip/blob/main/CTkToolTip/ctk_tooltip.py) (lines 111 to 116):

 ```
self.widget.bind("<Enter>", self.on_enter, add="+")'
 self.widget.bind("<Leave>", self.on_leave, add="+")
 self.widget.bind("<Motion>", self.on_enter, add="+")
 self.widget.bind("<B1-Motion>", self.on_enter, add="+")
 self.widget.bind("<Destroy>", lambda _: self.hide(), add="+")
```

And on [ctk_segmented_button.py](https://github.com/TomSchimansky/CustomTkinter/blob/master/customtkinter/windows/widgets/ctk_segmented_button.py), from CustomTkinter (lines 442 to 443):

```

     def bind(self, sequence=None, command=None, add=None):
         raise NotImplementedError

```

**Comment by Akascape** [comment]
@jipen Internal issue with ctk_segmented button, have to update that code from that side.

**Comment by jipen** [comment]
Ok.
And a great THANKS for what you do on the enhanced CTk widgets such as CTkListbox, CTkTooltip, CTkMessageBox or CTkTable !  👍👍👍
