### ISSUE TITLE
CTkToolTip not compatible with CTkMenuBar ??

### ISSUE THREAD

**Issue by matthew-efseaff** [Akascape/CTkToolTip#26]
I tried to add a tooltip to a menu selection:
```
from CTkMenuBar import *
from CTkToolTip import *
self.menu_bar = CTkMenuBar(self.root)
self.menu_bar = self.menu_bar.add_cascade(text='some option')
self.drop_menu = CustomDropdownMenu(widget=self.menu_bar)
self.drop_menu.add_option(option='some option', command=lambda: self.some_command())
self.drop_menu_tip = CTkToolTip(self.drop_menu, delay=0.1, message="some tooltip")
```
It's not showing up... is this possible in CTkToolTip?

**Comment by Akascape** [comment]
Where do you expect the tooltip to popup? Inside the dropdown menu or the button which opens it?

**Comment by matthew-efseaff** [comment]
Either works. I'd actually like to have just a button in the menu bar (have a button instead of have to .add_cascade), but didn't think that was possible.... 
As an example, possibly place the tooltip here, in the dropdown:
![image](https://github.com/Akascape/CTkToolTip/assets/150963343/88ff973d-80bc-436b-8c42-95a0a6c21522)

**Comment by Akascape** [comment]
The add_option method returns a button which is placed inside the dropdown, so pass that button to the tooltip.
```python
self.option_1 = self.drop_menu.add_option(option='some option', command=lambda: self.some_command())
self.drop_menu_tip = CTkToolTip(self.option_1, delay=0.1, message="some tooltip")
```
