### ISSUE TITLE
Feature Request - Word-Wrap: It would be handy to  have long text auto wrap

### ISSUE THREAD

**Issue by DLCIncluded** [Akascape/CTkToolTip#7]
This is a Feature request more than anything, but it would be really cool to have a feature to automatically wrap text if it is longer than XYZ or something. 
It is not a huge issue, as you can just manually enter newline(\n) into your message string, just thought I would suggest a possible feature to help everyone be lazy! 😄 

Thank you for this project either way, it saved me a load of time on my app!

**Comment by Akascape** [comment]
@DLCIncluded There is `wraplength` parameter for this. Please go through the documentation.

**Comment by DLCIncluded** [comment]
I am so sorry, idk how I missed that lol

Thank you! It's been A really long day..
Will close this out
