### ISSUE TITLE
Strange behaviour with widget scaling

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkToolTip#8]
Hi @Akascape. I am having some strange effects with CTkToolTip when I change the widget scaling on an app.

I reproduced this with complex_example.py. You can see the effects on this video:

https://github.com/Akascape/CTkToolTip/assets/89534395/02901650-61c4-4eea-9cce-5cdb853cbfff

My app has a preference option, which allows the user to change the widget scaling interactively. When the scaling is changed, the problem starts.

**Comment by Akascape** [comment]
@avalon60 Not experiencing this issue.
I tested this on ubuntu with widget scaling 0.8:
![Screenshot](https://github.com/Akascape/CTkToolTip/assets/89206401/e248b78a-56d5-4f45-88b9-6a1944830e88)

Make sure you are using the latest version of CTkTooltip.

**Comment by avalon60** [comment]
Hey @Akascape,  good news! I was using version 0.2 and just downloaded 0.4 and it fixed the issue.

Thanks!
