### ISSUE TITLE
Button label break tooltip hover action

### ISSUE THREAD

**Issue by AcidWeb** [Akascape/CTkToolTip#9]
Not sure if this is a bug or a general Tk limitation but it seems that hovering over the label of the button sometimes block the tooltip.

Mouse outside button text:
<img width="242" alt="image" src="https://github.com/Akascape/CTkToolTip/assets/3713734/cc573324-a3c0-4f03-b9ba-4aca7ded1131">

Mouse on button text:
<img width="127" alt="image" src="https://github.com/Akascape/CTkToolTip/assets/3713734/e52fa46f-ac80-4290-821a-52fd7f2a4a70">

**Comment by Akascape** [comment]
@AcidWeb Not facing this issue, make sure you are using the latest version.

**Comment by AcidWeb** [comment]
I'm using the latest version.

It looks like I can replicate issue only if `text` of the of the `CTkButton` was empty string and was changed after `CTkToolTip` was created. If I set initial `text` to anything else than empty string - everything start to work correctly.

**Comment by Akascape** [comment]
@AcidWeb I guess the issue is in customtkinter button then.
